from sqlalchemy import Column, Integer, String, Boolean, Enum, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database.database import Base
from app.models.enums import NotificationTypeEnum


class Notification(Base):
    """
    Per-user notification feed. Generated by services whenever a relevant
    event occurs (allocation, transfer, booking, maintenance, overdue, audit).
    """
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)

    type = Column(Enum(NotificationTypeEnum), nullable=False)
    message = Column(String(500), nullable=False)
    related_entity_type = Column(String(50), nullable=True)  # e.g. "asset", "booking"
    related_entity_id = Column(Integer, nullable=True)

    is_read = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="notifications")


class AuditLog(Base):
    """
    System-wide activity log: who did what, when.
    Distinct from asset "audit cycles" - this is the technical action trail.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)

    action = Column(String(150), nullable=False)  # e.g. "ASSET_CREATED", "ALLOCATION_APPROVED"
    entity_type = Column(String(50), nullable=True)
    entity_id = Column(Integer, nullable=True)
    details = Column(String(1000), nullable=True)

    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    user = relationship("User", back_populates="audit_logs")
